language: node_js
node_js:
  - "v6"
  - "stable"

cache:
  directories:
  - node_modules

branches:
  only:
    - master

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8 # C++11-compatible compiler for node > v4.0.0
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - "export CXX=g++-4.8"

script: npm test
